### ISSUE TITLE
Symantec CA doesn't seem to list any TLS extensions and CT

### ISSUE THREAD

**Issue by rhawk301** [pierky/sct-verify#4]
I am pretty sure they have been signing CT on all their certs, it is just this tool doesn't seem to recognize it.   Can it be modified to check all CT functions, or is there something else going on here?   I would love to be able and check all cert types for CT functions.   Thanks.

example server: gm.symcd.com
"No TLS extensions found."

**Comment by pierky** [comment]
Hello,

this script is meant to just verify SCTs served to clients using TLS Extensions, and not SCTs attached to certificates.

I tested the host you provided in the example using [Qualys SSL Server Test](https://www.ssllabs.com/ssltest/) and it also reports that the server doesn't send any TLS Extensions related to CT, SCT is only present in the certificate.

> Certificate Transparency | Yes (certificate)

Closing this; please feel free to reopen it if you think I didn't get the point or if you want to add more details.
